version: 2.1
orbs:
  build-tools: circleci/build-tools@2.7.0
executors:
  tests_executor:
    docker: # run the steps with Docker
      - image: cimg/openjdk:11.0.8
        environment:
          PGHOST: 127.0.0.1
      - image: circleci/postgres:11.8
        command: postgres -c max_connections=200
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
          PG_HOST: localhost
          POSTGRES_HOST_AUTH_METHOD: trust
          POSTGRES_PASSWORD: postgres
      - image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
        environment:
          - xpack.security.enabled: false
          - transport.host: localhost
          - network.host: 127.0.0.1
          - http.port: 9200
          - discovery.type: single-node
    resource_class: medium+

  machine_integration_test_exec:
    machine: # run the steps with Ubuntu VM
      image: ubuntu-2004:202010-01
    environment:
      PGHOST: 127.0.0.1
    resource_class: medium

common_filters: &common_filters
  filters:
    tags:
      only: /.*/
    branches:
      ignore:
        - gh-pages

workflows:
  version: 2
  everything:
    jobs:
      - build:
          <<: *common_filters

      - unit-tests:
          <<: *common_filters
          requires:
            - build
      - confidential-workflow-integration-tests:
          <<: *common_filters
          requires:
            - build
      - confidential-tool-integration-tests:
          <<: *common_filters
          requires:
            - build
      - integration-tests:
          <<: *common_filters
          requires:
            - build
      - singularity-tests:
          <<: *common_filters
          requires:
            - build


jobs:
  unit-tests:
    executor: tests_executor
    environment:
      TESTING_PROFILE: unit-tests
    steps:
      - setup_for_tests
      - run_tests
      - clean_and_save_cache
      - save_test_results
      - send_coverage

    #  - run:
    #      name: run the non-confidential integration tests
    #      command: |
    #        # Adding all "normal" certs into this local one that has the Hoverfly cert (instead of adding Hoverfly cert to the global one so it doesn't potentially affect other tests) 
    #        /usr/local/jdk-11.0.8/bin/keytool -importkeystore -srckeystore $JAVA_HOME/lib/security/cacerts -destkeystore LocalTrustStore -srcstorepass changeit -deststorepass changeit
    #        # mvn -B org.jacoco:jacoco-maven-plugin:report org.jacoco:jacoco-maven-plugin:report-aggregate clean install -Pnon-confidential-tests,coverage -Djavax.net.ssl.trustStore=../LocalTrustStore -Djavax.net.ssl.trustStorePassword=changeit  -DskipSignatureCheck=false -ntp
    #        mvn -B org.jacoco:jacoco-maven-plugin:report org.jacoco:jacoco-maven-plugin:report-aggregate clean install -Pnon-confidential-tests,coverage -Djavax.net.ssl.trustStore=../LocalTrustStore -Djavax.net.ssl.trustStorePassword=changeit -ntp
  singularity-tests:
    #executor: tests_executor
    executor: machine_integration_test_exec
    environment:
      TESTING_PROFILE: singularity-tests
    steps:
      - setup_machine
      - setup_for_tests

      - setup_machine_env_vars

      - setup_for_integration_tests
      - run_tests
      - clean_and_save_cache
      - save_test_results
      - send_coverage

  confidential-workflow-integration-tests:
    executor: tests_executor
    environment:
      TESTING_PROFILE: confidential-workflow-tests
    steps:
      - setup_remote_docker:
          version: 19.03.13
      - setup_for_tests
      - setup_for_integration_tests
      - run_tests
      - clean_and_save_cache
      - save_test_results

  confidential-tool-integration-tests:
    executor: tests_executor
    environment:
      TESTING_PROFILE: confidential-tool-tests
    steps:
      - setup_remote_docker:
          version: 19.03.13
      - setup_for_tests
      - setup_for_integration_tests
      - run_tests
      - clean_and_save_cache
      - save_test_results

  integration-tests:
    executor: tests_executor
    environment:
      TESTING_PROFILE: integration-tests
    steps:
      - setup_remote_docker:
          version: 19.03.13
      - setup_for_tests
      - setup_for_integration_tests
      - run_tests
      - clean_and_save_cache
      - save_test_results



  build:
    docker: # run the steps with Docker
      - image: cimg/openjdk:11.0.8
        environment:
          # Java can read cgroup. Sadly the cgroup in
          # CircleCI is wrong. Have to manually set. Nothing to do with surefire
          # plugin, it has its own JVM. The two of these must add up to a bit less than 4GB.
          JAVA_TOOL_OPTIONS: -Xmx512m
    steps: # a collection of executable commands
      - checkout # check out source code to working directory
      - restore_cache: # restore the saved cache after the first run or if `pom.xml` has changed
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          key: dockstore-cli-java-{{ checksum "pom.xml" }}
      - install_yq
      - install-git-secrets
      - install_confidential_test_data
      - run:
          name: build
          command: mvn -B clean install -DskipTests

        # Running scan must occur after build
      - run_git_secrets_scan
      - check_license_file
      - run:
          name: copy m2 manually
          command: cp -r ~/.m2 .
      - persist_to_workspace:
          root: .
          paths:
            - .






commands:
  setup_machine:
    steps:
      - attach_workspace:
          at: .
      - run: # Useful for verifying default versions on machine image
          name: Java/Maven/Python versions
          command: |
            java -version
            mvn -v
            python3 -V
      - run:
          name: Docker-Compose
          command: docker-compose up -d

  setup_machine_env_vars:
    steps:
      - run:
          name: Setup machine environment variables
          command: |
            echo "export PATH=/home/circleci/.local/bin:${PATH}" >> $BASH_ENV




  install_confidential_test_data:
    steps:
      - run:
          name: decrypt and expand confidential test data
          command: |
            sudo apt install openssl -y
            bash scripts/decrypt.sh

  send_coverage:
    steps:
      - run:
          name: send coverage
          command: bash <(curl -s https://codecov.io/bash) -F ${TESTING_PROFILE//-} || echo "Codecov did not collect coverage reports"

  install_dockerize_and_wait_for_db_and_es:
    steps:
      - run:
          name: install dockerize
          command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.6.1
      - run:
          name: Wait for db
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Wait for ES
          command: |
            wget --output-document /dev/null --waitretry=5 --tries=10 --retry-connrefused localhost:9200 || true

  check_license_file:
    steps:
      - run:
          name: check generated THIRD-PARTY-LICENCES.txt matches checked-in file
          command: |
            scripts/check-licenses.sh
          environment:
              TESTING_PROFILE: automated-review

  run_git_secrets_scan:
    steps:
      - run:
          name: Run git-secrets scan on dockstore repository
          # Needs to be after a build so that the correct configuration is set
          # by the exec-maven plugin
          command: |
            git secrets --scan

  clean_and_save_cache:
    steps:
      - run:
          name: clean the cache
          command: |
            rm -rf ~/.m2/repository/io/dockstore
            rm -rf ~/.m2/repository/.cache/download-maven-plugin directory
      - save_cache: # saves the project dependencies
          paths:
            - ~/.m2
          key: dockstore-cli-java-{{ checksum "pom.xml" }}

  install_yq:
    steps:
      - run:
          name: Install yq
          command: |
            wget https://github.com/mikefarah/yq/releases/download/3.3.2/yq_linux_amd64
            chmod a+x yq_linux_amd64
            sudo mv yq_linux_amd64 /usr/bin/yq

  install-git-secrets:
    steps:
      - run:
          name: Install git-secrets
          command: |
            wget --no-verbose -O git-secrets-1.3.0.tar.gz https://github.com/awslabs/git-secrets/archive/1.3.0.tar.gz
            tar -zxf git-secrets-1.3.0.tar.gz
            cd git-secrets-1.3.0
            sudo make install

  setup_postgres:
    steps:
      - run:
          name: setup postgres user and DB
          command: |
            psql -c "create user dockstore with password 'dockstore' createdb;" -U postgres
            psql -c 'create database webservice_test with owner = dockstore;' -U postgres
            psql -c "ALTER USER dockstore WITH superuser;" -U postgres

  install_postgres_sql_client:
    steps:
     - run:
         name: Install postgresql client
         command: |
           sudo rm -rf /var/lib/apt/lists/*
           sudo apt update
           sudo apt install -y postgresql-client

  setup_for_tests:
    steps:
      - attach_workspace:
          at: .
      - restore_cache: # restore the saved cache after the first run or if `pom.xml` has changed
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          key: dockstore-java-{{ checksum "pom.xml" }}
      - run:
          name: manually copy back .m2
          command: cp -r .m2 ~/.m2
      - install_yq
      - install_postgres_sql_client
      - setup_postgres
      - install_dockerize_and_wait_for_db_and_es


  setup_for_integration_tests:
    steps:
      - run:
          name: install pip
          command: |
            sudo apt update
            sudo apt install python3-distutils python3-dev
            curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
            python3 get-pip.py
            # For debug purposes, a python3 version was installed in the image, pip is untagged
            python3 --version
            pip3 --version
      # https://circleci.com/docs/2.0/env-vars/#using-parameters-and-bash-environment
      - run:
          name: Setup pip dependencies environment variables
          command: |
            export GO_PATH=/usr/local
            echo "export GO_PATH=/usr/local" >> $BASH_ENV
            export SINGULARITY_PATH=${HOME}/go
            echo "export SINGULARITY_PATH=${HOME}/go" >> $BASH_ENV
            echo "export PATH=${GO_PATH}/go/bin:${PATH}:${SINGULARITY_PATH}/bin" >> $BASH_ENV
      - run:
          name: install pip dependencies
          command: scripts/install-tests.sh
      - install_confidential_test_data

  run_tests:
    steps:
      - run:
          name: "What is TESTING PROFILE?"
          command: echo "TESTING PROFILE is:" ${TESTING_PROFILE}
      - run:
          name: run test
          command: mvn -B org.jacoco:jacoco-maven-plugin:report org.jacoco:jacoco-maven-plugin:report-aggregate clean install -P$TESTING_PROFILE,coverage -ntp


  save_test_results:
    steps:
      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/target/.*-reports/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results


