name: Deploy develop snapshot

on:
  push:
    branches-ignore:
      - 'master'
      - 'release/**'
      - 'hotfix/**'
      - 'dependabot/**'

  workflow_dispatch:
  
jobs:
  build:
    uses: dockstore/workflow-actions/.github/workflows/deploy_snapshot.yaml@seab-6771/reusable-image-deploy
    secrets: inherit