name: Tagged release deploy

on:
  push:
    tags: 
      - '**'

jobs:
  call-reusable-tagged-release:
    uses: dockstore/workflow-actions/.github/workflows/deploy_artifacts.yaml@seab-6771/reusable-image-deploy
    secrets: inherit
